// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Infrastructure.DatabaseContext;

#nullable disable

namespace TaskManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiTaskManager.Core.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfStart")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeamSize")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("d8f1e128-1d1d-4f53-a8cc-bd79217b2a05"),
                            DateOfStart = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Migration complète de l'infrastructure vers Azure avec automatisation CI/CD.",
                            ProjectName = "Migration Cloud Azure",
                            TeamSize = 6
                        },
                        new
                        {
                            ProjectId = new Guid("1a12e199-b289-4d38-961e-12345876abcd"),
                            DateOfStart = new DateTime(2022, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Développement d'une application mobile pour la gestion RH en interne.",
                            ProjectName = "Application RH Mobile",
                            TeamSize = 4
                        },
                        new
                        {
                            ProjectId = new Guid("34cd5c45-0f7a-4f1c-8ee9-98765432abcd"),
                            DateOfStart = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Refonte complète de la plateforme e-commerce avec Angular et .NET Core.",
                            ProjectName = "Refonte e-commerce",
                            TeamSize = 8
                        },
                        new
                        {
                            ProjectId = new Guid("a341f66b-98cb-40b7-a6a2-90f3b33cf010"),
                            DateOfStart = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Création d'une API pour la cartographie des utilisateurs à l'international.",
                            ProjectName = "API géolocalisation",
                            TeamSize = 3
                        },
                        new
                        {
                            ProjectId = new Guid("e109eabc-12aa-42ff-9090-aba123aa3456"),
                            DateOfStart = new DateTime(2023, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Développement d'une solution IoT pour surveiller les machines en temps réel.",
                            ProjectName = "Monitoring industriel",
                            TeamSize = 5
                        },
                        new
                        {
                            ProjectId = new Guid("fda43c8b-c503-4f5b-81e1-1098ae01bcde"),
                            DateOfStart = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Développement d’un outil CRM adapté aux besoins d’un client BTP.",
                            ProjectName = "Outil CRM sur mesure",
                            TeamSize = 7
                        },
                        new
                        {
                            ProjectId = new Guid("bd123c8a-9832-4ed8-a1b5-7ab32ca45678"),
                            DateOfStart = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Plateforme de réservation multilingue pour des services médicaux.",
                            ProjectName = "Système de réservation",
                            TeamSize = 4
                        },
                        new
                        {
                            ProjectId = new Guid("9be8f999-cccd-44d7-a4f1-5eaa87654321"),
                            DateOfStart = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Projet de traitement de gros volumes de données clients pour recommandations.",
                            ProjectName = "Analyse Big Data",
                            TeamSize = 9
                        },
                        new
                        {
                            ProjectId = new Guid("2c34e0d9-21dd-4f8c-bb6a-b7fdfabcd123"),
                            DateOfStart = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Mise en place d’un chatbot IA pour le recrutement automatique sur LinkedIn.",
                            ProjectName = "Bot de recrutement",
                            TeamSize = 2
                        },
                        new
                        {
                            ProjectId = new Guid("889fa0a1-435f-42b0-b254-cccdeedc0001"),
                            DateOfStart = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectDescription = "Développement d’un tableau de bord interactif avec Power BI et Blazor.",
                            ProjectName = "Dashboard analytique",
                            TeamSize = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
